version: 2
updates:
  # Github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  
  # Provider Go module
  - package-ecosystem: "gomod"
    directory: "./provider"
    schedule:
      interval: "weekly"
    assignees:
      - "pandatix"

  # SDK Go module
  - package-ecosystem: "gomod"
    directory: "./sdk"
    schedule:
      interval: "weekly"
    assignees:
      - "pandatix"

  # Examples Go module
  - package-ecosystem: "gomod"
    directory: "./examples"
    schedule:
      interval: "weekly"
    assignees:
      - "pandatix"

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /examples
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /provider
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /sdk/dotnet
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /sdk
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /sdk/nodejs
    schedule:
      interval: daily
